env:
  browser: true
  es6: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - ./tsconfig.json
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
reportUnusedDisableDirectives: true
overrides:
  - files:
      - '*.ts'
    rules:
      default-case: off
      consistent-return: off
  - files:
      - 'src/migrations/*-*.ts'
  - files:
      - '*.test.ts'
    rules:
      '@typescript-eslint/unbound-method': off

rules:
  '@typescript-eslint/explicit-module-boundary-types': error
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn: false